routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\FrontHomeController;
use App\Http\Controllers\Back\BackHomeController;

// FRONT DESIGN
Route::prefix('front')->name('front.')->group(function () {
    Route::get('/', FrontHomeController::class)->middleware('auth')->name('index');
});

require __DIR__ . '/auth.php';

// BACK DESIGN
Route::prefix('back')->name('back.')->group(function () {
    Route::get('/', BackHomeController::class)->middleware('admin')->name('index');

    ##------------------------------------------------------- USERS MODULE
    Route::controller(UserController::class)->group(function () {
        Route::resource('users', UserController::class);
    });

    ##------------------------------------------------------- ROLES MODULE
    Route::controller(RoleController::class)->group(function () {
        Route::resource('roles', RoleController::class);
    });

    ##------------------------------------------------------- ADMINS MODULE
    Route::controller(AdminController::class)->group(function () {
        Route::resource('admins', AdminController::class);
    });

    require __DIR__ . '/adminAuth.php';
});

Route::get('/', function () {
    return view('welcome');
});

app/Http/Controllers/Back/BackHomeController.php
<?php

namespace App\Http\Controllers\Back;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BackHomeController extends Controller
{
    /**
     * Handle the incoming request.
     */
    public function __invoke(Request $request)
    {
        return view('back.home');
    }
}

resources/views/back/admins/create.blade.php
<form action="{{ route('back.admins.store') }}" method="post" id="add_form" enctype="multipart/form-data">
    @csrf

    <div id="add_form_messages"></div>

    {{-- MODIFICATIONS FROM HERE --}}
    <div class="row">
        <div class="form-group col-md-6">
            <label class="form-label">{{ __('lang.name') }}</label>
            <input type="text" class="border form-control" name="name"
                placeholder="{{ __('lang.please_enter') }} {{ __('lang.name') }}...">
        </div>

        <div class="form-group col-md-6">
            <label class="form-label">{{ __('lang.email') }}</label>
            <input type="email" class="border form-control" name="email"
                placeholder="{{ __('lang.please_enter') }} {{ __('lang.email') }}...">
        </div>

        <div class="form-group col-md-12">
            <label class="form-label">{{ __('lang.role') }}</label>
            <select class="border form-control" name="role">
                <option value="">{{ __('lang.select_role') }}</option>
                @foreach ($roles as $role)
                    <option value="{{ $role->name }}">{{ $role->name }}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group col-6">
            <label class="form-label">{{ __('lang.password') }}</label>
            <input type="password" class="border form-control" name="password"
                placeholder="{{ __('lang.please_enter') }} {{ __('lang.password') }}...">
        </div>

        <div class="form-group col-6">
            <label class="form-label">{{ __('lang.password_confirmation') }}</label>
            <input type="password" class="border form-control" name="password_confirmation"
                placeholder="{{ __('lang.please_enter') }} {{ __('lang.password_confirmation') }}...">
        </div>
    </div>
    {{-- MODIFICATIONS TO HERE --}}

    <hr class="text-muted">

    <div class="form-group float-end">
        <button type="button" class="btn btn-light" data-bs-dismiss="modal">{{ __('lang.close') }}</button>
        <button type="button" class="btn btn-primary" id="submit_add_form">{{ __('lang.submit') }}</button>
    </div>
</form>

resources/views/back/admins/edit.blade.php
<form action="{{ route('back.admins.update', ['admin' => $admin]) }}" method="post" id="edit_form"
    enctype="multipart/form-data">
    @csrf
    @method('PUT')

    <div id="edit_form_messages"></div>

    {{-- MODIFICATIONS FROM HERE --}}
    <div class="row">
        <div class="form-group col-md-6">
            <label class="form-label">{{ __('lang.name') }}</label>
            <input type="text" class="border form-control" name="name"
                placeholder="{{ __('lang.please_enter') }} {{ __('lang.name') }}..." value="{{ $admin->name }}">
        </div>

        <div class="form-group col-md-6">
            <label class="form-label">{{ __('lang.email') }}</label>
            <input type="email" class="border form-control" name="email"
                placeholder="{{ __('lang.please_enter') }} {{ __('lang.email') }}..." value="{{ $admin->email }}">
        </div>

        {{-- <div class="form-group col-md-12">
            <label class="form-label">{{ __('lang.role') }}</label>
            <select class="border form-control" name="role">
                <option value="">{{ __('lang.select_role') }}</option>
                @foreach ($roles as $item)
                    <option value="{{ $item->name }}" @selected($admin->hasRole($item->name))>{{ $item->name }}</option>
                @endforeach
            </select>
        </div> --}}

        <div class="form-group col-6">
            <label class="form-label">{{ __('lang.password') }}</label>
            <input type="password" class="border form-control" name="password"
                placeholder="{{ __('lang.please_enter') }} {{ __('lang.password') }}...">
        </div>

        <div class="form-group col-6">
            <label class="form-label">{{ __('lang.password_confirmation') }}</label>
            <input type="password" class="border form-control" name="password_confirmation"
                placeholder="{{ __('lang.please_enter') }} {{ __('lang.password_confirmation') }}...">
        </div>
    </div>
    {{-- MODIFICATIONS TO HERE --}}

    <hr class="text-muted">

    <div class="form-group float-end">
        <button type="button" class="btn btn-light" data-bs-dismiss="modal">{{ __('lang.close') }}</button>
        <button type="button" class="btn btn-primary" id="submit_edit_form">{{ __('lang.submit') }}</button>
    </div>
</form>

resources/views/back/admins/filter.blade.php
@php
    $modelName = App\Models\Admin::class;
@endphp

<x-filteration :modelName="$modelName">

        <div class="row">
    
            <div class="col-md-8">
                <label class="label-filter">{{ __('lang.word') }}</label>
                <input type="text" name="word" class="form-control" placeholder="{{ __('lang.please_enter') }} {{ __('lang.word') }}" value="{{ request()->input('word') }}">
            </div>

            <div class="col-md-4">
                <label class="label-filter">{{ __('lang.date') }}</label>
                <div class="input-daterange input-group" id="datepicker6" data-date-format="yyyy-mm-dd" data-date-autoclose="true" data-provide="datepicker" data-date-container='#datepicker6'>
                    <input type="date" class="form-control" name="start" placeholder="{{ __('lang.date_from') }}" value="{{ request()->input('start') }}"/>
                    <input type="date" class="form-control" name="end" placeholder="{{ __('lang.date_to') }}" value="{{ request()->input('end') }}"/>
                </div>
            </div>

        </div>

</x-filteration>

resources/views/back/admins/index.blade.php
@extends('back.master')
@section('title', __('lang.admins'))
@section('admins_active', 'active bg-light')
@includeIf("$directory.pushStyles")

@section('content')
    <!-- page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                <h2 class="h5 page-title">{{ __('lang.admins') }}</h2>

                <div class="page-title-right">
                    {{-- @if (permission(['add_admins'])) --}}
                    <a href="{{ route('back.admins.create') }}" data-title="{{ __('lang.add_new_admin') }}" id="add_btn"
                        class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#mainModal">
                        {{ __('lang.add_new') }}
                    </a>
                    {{-- @endif --}}
                </div>
            </div>
        </div>
    </div>

    {{-- Table --}}
    <div class="card mt-3" id="mainCont">
        <div class="card-body">

            {{-- Table --}}
            <div class="table-responsive">
                <table class="table align-middle table-nowrap font-size-14">
                    <thead class="bg-light">
                        <tr>
                            <th class="text-primary" width="5%">#</th>
                            <th class="text-primary">{{ __('lang.name') }}</th>
                            <th class="text-primary">{{ __('lang.email') }}</th>
                            <th class="text-primary">{{ __('lang.role') }}</th>
                            <th class="text-primary" width="11%">{{ __('lang.actions') }}</th>
                        </tr>
                    </thead>

                    <tbody>
                        @if (count($data['data']) > 0)
                            @foreach ($data['data'] as $key => $item)
                                <tr>
                                    <td>{{ $data['data']->firstItem() + $loop->index }}</td>
                                    <td>{{ $item->name }}</td>
                                    <td>{{ $item->email }}</td>
                                    <td>
                                        @if (count($item->getRoleNames()) > 0)
                                            <span class="badge bg-warning text-white p-2">
                                                {{ $item->getRoleNames()[0] ?? '' }}
                                            </span>
                                        @endif
                                    </td>
                                    <td>
                                        <div class="btn-group">
                                            <button class="btn btn-primary dropdown-toggle btn-sm" type="button"
                                                data-bs-toggle="dropdown" aria-expanded="false">
                                                {{ __('lang.actions') }} <i class="mdi mdi-chevron-down"></i>
                                            </button>
                                            <div class="dropdown-menu">

                                                <a href="{{ route('back.admins.show', ['admin' => $item]) }}"
                                                    class="dropdown-item displayClass"
                                                    data-title="{{ __('lang.show_admin') }}" data-bs-toggle="modal"
                                                    data-bs-target="#mainModal">
                                                    <span class="bx bx-show-alt"></span>
                                                    {{ __('lang.show') }}
                                                </a>

                                                {{-- @if (permission(['edit_admins'])) --}}
                                                <a href="{{ route('back.admins.edit', ['admin' => $item]) }}"
                                                    class="dropdown-item editClass"
                                                    data-title="{{ __('lang.edit_admin') }}" data-bs-toggle="modal"
                                                    data-bs-target="#mainModal">
                                                    <span class="bx bx-edit-alt"></span>
                                                    {{ __('lang.edit') }}
                                                </a>
                                                {{-- @endif --}}

                                                {{-- @if (permission(['delete_admins'])) --}}
                                                <a class="dropdown-item deleteClass"
                                                    href="{{ route('back.admins.destroy', ['admin' => $item]) }}"
                                                    data-title="{{ __('lang.delete_admin') }}" data-bs-toggle="modal"
                                                    data-bs-target="#deleteModal">
                                                    <span class="bx bx-trash-alt"></span>
                                                    {{ __('lang.delete') }}
                                                </a>
                                                {{-- @endif --}}

                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        @else
                            <x-empty-alert></x-empty-alert>
                        @endif
                    </tbody>
                </table>
            </div>

            {{ $data['data']->appends(request()->query())->render('pagination::bootstrap-4') }}

        </div>
    </div>
@endsection

@includeIf("$directory.scripts")
@includeIf("$directory.pushScripts")

resources/views/back/admins/pushScripts.blade.php
@push('scripts')
    
@endpush

resources/views/back/admins/pushStyles.blade.php
@push('style')
  
@endpush

resources/views/back/admins/scripts.blade.php
<script src="{{ asset('assets-back') }}/jquery-3.6.0.min.js"></script>
<script>
    $("document").ready(function() {
        //============================================= LOADER
        var $loading = $('#loading').hide();
        $(document)
            .ajaxStart(function() {
                $loading.show();
            })
            .ajaxStop(function() {
                $loading.hide();
            });

        //============================================= AJAX REQUEST FOR SHOWING ADD NEW RECORD MODAL
        $(document).on('click', "#add_btn", function(e) {
            e.preventDefault();
            let url = $(this).attr("href");
            let title = $(this).attr("data-title");
            $("#modal-title").html(title);
            $.ajax({
                url: url,
                method: "get",
                success: function(data) {
                    $("#modal-body").html(data);
                },
                error: function() {
                    alert("Please try again ... ");
                }
            });
        });

        //============================================= AJAX REQUEST FOR ADDING RECORD
        $(document).on('click', "#submit_add_form", function() {
            let theForm = $("#add_form");
            let formAction = theForm[0].action;
            let formMethod = theForm[0].method;
            let formData = new FormData($('#add_form')[0]);

            $.ajax({
                url: formAction,
                method: formMethod,
                data: formData,
                processData: false,
                contentType: false,
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                dataType: "json",
                success: function(data) {
                    $('#add_form').find('small').remove();
                    $("#add_form_messages").empty().removeClass()
                        .addClass('alert alert-success').append(data['success'])
                        .get(0).scrollIntoView({
                            behavior: 'instant',
                            block: 'center'
                        });

                    setTimeout(function() {
                        $(':input', '#add_form')
                            .not(':button, :submit, :reset, :hidden')
                            .val('')
                            .prop('checked', false)
                            .prop('selected', false);
                        $("#add_form_messages").empty().removeClass();
                        $("#mainModal").modal('hide');
                        $("#mainCont").load(" #mainCont > *");
                    }, 1000);
                },
                error: function(xhr) {
                    $('#add_form').find('small').remove();
                    $.each(xhr.responseJSON.errors, function(key, value) {
                        let el = $(document).find('[name="' + key + '"]').first();
                        el.after($('<small class="text-danger">' + value[0] +
                            '</small>'));
                    });
                },
            });
        });

        //============================================= AJAX REQUEST FOR SHOWING DELETE MODAL
        $(document).on('click', ".deleteClass", function(e) {
            let url = $(this).attr("href");
            let title = $(this).attr("data-title");
            $("#delete-modal-title").html(title);
            $("#submit_delete").attr("href", url);
        });

        //============================================= AJAX REQUEST FOR DELETING RECORD
        $(document).on('click', "#submit_delete", function(e) {
            e.preventDefault();
            let url = $(this).attr("href");
            $.ajax({
                url: url,
                method: 'DELETE',
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                dataType: "json",
                success: function(data) {
                    $("#delete_alert_div").removeClass().addClass('alert alert-success')
                        .append(data['success']);

                    setTimeout(function() {
                        $("#mainCont").load(" #mainCont > *");
                        $("#deleteModal").load(" #deleteModal > *");
                        $('#deleteModal').modal('toggle');
                    }, 1000);
                },
                error: function() {
                    alert("Please try again ...");
                }
            });
        });

        //============================================= SCRIPT FOR SHOWING EDITING MODAL
        $(document).on('click', ".editClass", function(e) {
            e.preventDefault();
            let url = $(this).attr("href");
            let title = $(this).attr("data-title");
            $("#modal-title").html(title);
            $.ajax({
                url: url,
                method: "get",
                success: function(data) {
                    $("#modal-body").html(data);
                },
                error: function() {
                    alert("Please try again ... ");
                }
            });
        });

        //============================================= AJAX REQUEST FOR UPDATING
        $(document).on('click', "#submit_edit_form", function() {
            let theForm = $("#edit_form");
            let formAction = theForm[0].action;
            let formMethod = theForm[0].method;
            let formData = new FormData($('#edit_form')[0]);

            $.ajax({
                url: formAction,
                method: formMethod,
                data: formData,
                processData: false,
                contentType: false,
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                dataType: "json",
                success: function(data) {
                    $('#edit_form').find('small').remove();
                    $("#edit_form_messages").empty().removeClass()
                        .addClass('alert alert-success').append(data['success'])
                        .get(0).scrollIntoView({
                            behavior: 'instant',
                            block: 'center'
                        });

                    setTimeout(function() {
                        $("#mainCont").load(" #mainCont > *");
                        $("#edit_form_messages").empty().removeClass();
                        $("#mainModal").modal('hide');
                    }, 1000);
                },
                error: function(xhr) {
                    $('#edit_form').find('small').remove();
                    $.each(xhr.responseJSON.errors, function(key, value) {
                        let el = $(document).find('[name="' + key + '"]').first();
                        el.after($('<small class="text-danger">' + value[0] +
                            '</small>'));
                    });
                }
            });

        });

        //============================================= SCRIPT FOR DISPLAYING RECORD DETAILS ON MODAL
        $(document).on('click', ".displayClass", function(e) {
            e.preventDefault();
            let formAction = $(this).attr("href");
            let title = $(this).attr("data-title");
            $("#modal-title").html(title);
            $.ajax({
                url: formAction,
                method: "get",
                success: function(data) {
                    $("#modal-body").html(data);
                },
                error: function() {
                    alert("failed .. Please try again !");
                }
            });
        });
    });
</script>

resources/views/back/admins/show.blade.php
{{-- MODIFICATIONS FROM HERE --}}
<div class="row">
    <div class="form-group col-md-6">
        <label class="form-label">{{ __('lang.name') }}</label>
        <p class="border form-control">{{ $admin->name ?? '--' }}</p>
    </div>

    <div class="form-group col-md-6">
        <label class="form-label">{{ __('lang.email') }}</label>
        <p class="border form-control">{{ $admin->email ?? '--' }}</p>
    </div>

    <div class="form-group col-12">
        <label class="form-label">{{ __('lang.role') }}</label>
        <p class="border form-control mb-1">{{ $admin->getRoleNames()[0] ?? '--' }}</p>
    </div>
</div>
{{-- MODIFICATIONS TO HERE --}}

<hr class="text-muted">

<div class="form-group float-end">
    <button type="button" class="btn btn-light" data-bs-dismiss="modal">{{ __('lang.close') }}</button>
</div>